# Generated by Django 4.0.2 on 2022-02-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainevent', '0003_auto_20220208_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(help_text='Enter your Roll No. if you are studying in TIET otherwise enter your college name', max_length=100, verbose_name='Roll no/ College Name'),
        ),
    ]
