# Generated by Django 4.0.2 on 2022-02-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainevent', '0004_alter_user_first_name_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='are_you_a_thapar_student',
        ),
    ]
