# Generated by Django 4.0.2 on 2022-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6)),
                ('case_study_link', models.URLField(max_length=1000, null=True)),
                ('case_study_name', models.CharField(max_length=50, null=True)),
                ('presentation', models.FileField(default='competition/presentation/default.png', upload_to='presentation/')),
            ],
        ),
    ]
