# Generated by Django 4.0.2 on 2022-02-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='case_study_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='case_study_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='presentation',
            field=models.FileField(blank=True, default='competition/presentation/default.png', upload_to='presentation/'),
        ),
    ]
