# Generated by Django 3.1 on 2022-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_preevent_member2_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
