# Generated by Django 4.0.2 on 2022-02-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_preevent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preevent',
            name='Member1_discordid',
        ),
        migrations.RemoveField(
            model_name='preevent',
            name='Member2_discordid',
        ),
    ]
