# Generated by Django 4.0.2 on 2022-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_remove_preevent_member1_discordid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preevent',
            name='Member1_discordid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preevent',
            name='Member2_discordid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
